---
# Kubernetes Deployment for NASA App with Persistent Volume and CronJob
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nasa-app
  namespace: nasa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nasa-app
  template:
    metadata:
      labels:
        app: nasa-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000" 
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: nasa-app
          image: barransapapa/nasa-app:latest
          ports:
          - containerPort: 5000
          env:
            - name: NASA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nasa-api-key
                  key: apiKey         
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: log-pvc
---
# Persistent Volume Claim for NASA App logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
  namespace: nasa
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: ""
  volumeName: log-pv-1
---
# CronJob to fetch asteroid data every two minutes
apiVersion: batch/v1
kind: CronJob
metadata:
  name: asteroids-cronjob
  namespace: nasa
spec:
  schedule: "*/2 * * * *"  # Runs every two minutes
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fetch-asteroids
            image: curlimages/curl:7.85.0
            command: ["/bin/sh", "-c"]
            args:
              - |
                curl http://nasa-app-service.nasa.svc.cluster.local:5000/asteroids
          restartPolicy: Never