apiVersion: apps/v1
kind: Deployment
metadata:
  name: nasa-app
  namespace: nasa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nasa-app
  template:
    metadata:
      labels:
        app: nasa-app
    spec:
      containers:
        - name: nasa-app
          image: barransapapa/nasa-app:latest
          env:
            - name: NASA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nasa-api-key
                  key: apiKey
          ports:
            - containerPort: 5000
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: asteroids-cronjob
  namespace: nasa
spec:
  schedule: "*/3 * * * *"  # Runs every two minutes
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fetch-asteroids
            image: curlimages/curl:7.85.0
            command: ["/bin/sh", "-c"]
            args:
              - |
                curl http://nasa-app-service.nasa.svc.cluster.local:5000/asteroids
          restartPolicy: Never