# Kubernetes Service for NASA App with Prometheus Annotations
apiVersion: v1
kind: Service
metadata:
  name: nasa-app-service
  namespace: nasa
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  selector:
    app: nasa-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30009