apiVersion: v1
kind: Service
metadata:
  name: nasa-app-service
  namespace: nasa
spec:
  type: NodePort
  selector:
    app: nasa-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30009