---
- name: Deploy nasa namespace
  hosts: all
  tasks:
    - name: Create nasa Namespace
      k8s:
        state: present
        definition: 
          apiVersion: v1
          kind: Namespace
          metadata:
            name: nasa